EXP_NAME: KOBIGBIRD
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: KOBIGBIRD
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/KOBIGBIRD_w4096
    PARAMETERS:
        max_word_len: 4096

TOKENIZER:
    name: kobigbird
    
MODEL:
    modelname: kobigbird
    PARAMETERS:
        pretrained_name: 'monologg/kobigbird-bert-base'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: null

TRAIN:
    batch_size: 2
    num_training_steps: 10000
    accumulation_steps: 1
    num_workers: 12
    use_wandb: True

LOG:
    log_interval: 1
    eval_interval: 1000

OPTIMIZER:
    lr: 0.00001
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: '/saved_model/Part1'