EXP_NAME: KOBIGBIRD
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - validation
        - test

DATASET:
    name: KOBIGBIRD
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/KOBIGBIRD_w4096
    PARAMETERS:
        max_word_len: 4096

TOKENIZER:
    name: kobigbird

MODEL:
    modelname: kobigbird
    PARAMETERS:
        pretrained_name: 'monologg/kobigbird-bert-base'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: /saved_model/Part1/KOBIGBIRD/best_model.pt

TRAIN:
    batch_size: 64
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: '/saved_model/Part1'
    result_name: results
