EXP_NAME: DualBERT-bow_content_category_select
SEED: 223

MODE:
  do_train: false
  do_test: true
  test_list:
  - train
  - validation
  - test

DATASET:
  name: DualBERT
  data_path: ../data/Part1
  saved_data_path: ../data-direct/bow_content_category_select/DualBERT_w512
  PARAMETERS:
    max_word_len: 512
    max_category_len: 128
  direct_path: ../data-direct/bow_content_category_select

TOKENIZER:
  name: bert
  pretrained_model_name_or_path: 'skt/kobert-base-v1'
  
MODEL:
  modelname: dualbert
  PARAMETERS:
    pretrained_name: skt/kobert-base-v1
    num_classes: 2
  CHECKPOINT:
    checkpoint_path: ./saved_model-direct/bow_content_category_select/DualBERT-bow_content_category_select/best_model.pt
TRAIN:
  batch_size: 32
  num_workers: 12
LOG:
  log_interval: 10
RESULT:
  savedir: ./saved_model-direct/bow_content_category_select
  result_name: results
