EXP_NAME: T5EncNet-sentence_embedding_content_category_select
SEED: 223
MODE:
  do_train: false
  do_test: true
  test_list:
  - train
  - validation
  - test
DATASET:
  name: T5EncNet
  data_path: ../data/Part1
  saved_data_path: ../data-direct/sentence_embedding_content_category_select/T5EncNet_w512
  PARAMETERS:
    max_source_length: 512
  direct_path: ../data-direct/sentence_embedding_content_category_select
TOKENIZER:
  name: t5encnet
MODEL:
  modelname: t5encnet
  PARAMETERS:
    pretrained_name: KETI-AIR/ke-t5-small-newslike
    pooler: max
    num_classes: 2
    T5Gen_path: ./part1_title/saved_model-direct/sentence_embedding_content_category_select/T5Gen-sentence_embedding_content_category_select/latest_model.pt
  CHECKPOINT:
    checkpoint_path: ./saved_model-direct/sentence_embedding_content_category_select/T5EncNet-sentence_embedding_content_category_select/best_model.pt
TRAIN:
  batch_size: 64
  num_workers: 12
LOG:
  log_interval: 10
RESULT:
  savedir: ./saved_model-direct/sentence_embedding_content_category_select
  result_name: results
