EXP_NAME: DualBERT-ngram_title_category_select
SEED: 223
MODE:
    save_list:
        - train
        - validation
        - test
DATASET:
  name: DualBERT
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_word_len: 512
    max_category_len: 128
  direct_path: ../data-direct/ngram_title_category_select
TOKENIZER:
  name: bert
TRAIN:
  batch_size: 256
  num_workers: 12
RESULT:
  savedir: ../data-direct/ngram_title_category_select
  dataname: DualBERT_w512
