EXP_NAME: BERT-bow_content_category_select
SEED: 223
MODE:
    save_list:
        - train
        - validation
        - test
DATASET:
  name: BERT
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_word_len: 512
  direct_path: ../data-direct/bow_content_category_select
TOKENIZER:
  name: bert
TRAIN:
  batch_size: 256
  num_workers: 0
RESULT:
  savedir: ../data-direct/bow_content_category_select
  dataname: BERT_w512
