EXP_NAME: RoBERTa_DualBERT-ngram_title_category_select
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - validation
        - test

DATASET:
    name: RoBERTa_DualBERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data-direct/ngram_title_category_select/RoBERTa_DualBERT_w512
    PARAMETERS:
        max_word_len: 512
        max_category_len: 128
    direct_path: ../data-direct/ngram_title_category_select

TOKENIZER:
    name: RoBERTa_dualbert

MODEL:
    modelname: RoBERTa_dualbert
    PARAMETERS:
        pretrained_name: 'klue/roberta-base'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: ./saved_model-direct/ngram_title_category_select/RoBERTa_DualBERT-ngram_title_category_select/best_model.pt

TRAIN:
    batch_size: 64
    num_workers: 0

LOG:
    log_interval: 10

RESULT:
    savedir: ./saved_model-direct/ngram_title_category_select
    result_name: results