EXP_NAME: T5EncNet-ngram_title_category_select
SEED: 223
MODE:
  do_train: true
  do_test: false
DATASET:
  name: T5EncNet
  data_path: ../data/Part1
  saved_data_path: ../data-direct/ngram_title_category_select/T5EncNet_s512_t128
  PARAMETERS:
    max_source_length: 512
  direct_path: ../data-direct/ngram_title_category_select
TOKENIZER:
  name: KETI-AIR/ke-t5-small-newslike
MODEL:
  modelname: t5encnet
  PARAMETERS:
    pretrained_name: KETI-AIR/ke-t5-small-newslike
    pooler: max
    num_classes: 2
    T5Gen_path: ./part1_title/saved_model-direct/ngram_title_category_select/T5Gen-ngram_title_category_select/latest_model.pt
  CHECKPOINT:
    checkpoint_path: null
TRAIN:
  batch_size: 8
  num_training_steps: 1
  accumulation_steps: 10000
  num_workers: 12
  use_wandb: true
LOG:
  log_interval: 1
  eval_interval: 1000
OPTIMIZER:
  lr: 1.0e-03
  weight_decay: 0.0005
SCHEDULER:
  warmup_ratio: 0.1
  use_scheduler: true
RESULT:
  savedir: ./saved_model-direct/ngram_title_category_select
