EXP_NAME: T5Gen-bow_content_category_select
SEED: 223
MODE:
    save_list:
        - train
        - validation
        - test
DATASET:
  name: T5Gen
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_source_length: 512
    max_target_length: 128
  direct_path: ../data-direct/bow_content_category_select
TOKENIZER:
  name: KETI-AIR/ke-t5-small-newslike
TRAIN:
  batch_size: 256
  num_workers: 12
RESULT:
  savedir: ../data-direct/bow_content_category_select
  dataname: T5Gen_s512_t128
