EXP_NAME: BERT_Sims_Stop_Gradient-bow_title_category_select
SEED: 223
MODE:
  save_list:
    - train
    - validation
    - test
DATASET:
  name: BERT_CAT_CONT_LEN
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_word_len: 512
  direct_path: ../data-direct/bow_title_category_select
  CAT_KEYS: ["newsCategory","newsSubcategory","partNum","processType","processPattern","processLevel"]

TOKENIZER:
  name: bert
TRAIN:
  batch_size: 1024
  num_workers: 12
RESULT:
  savedir: ../data-direct/bow_title_category_select
  dataname: BERT_CAT_CONT_LEN_w512
