EXP_NAME: RoBERTa_DualBERT-sentence_embedding_content_category_select
SEED: 223
    
MODE:
    save_list:
        - train
        - validation
        - test

DATASET:
    name: RoBERTa_DualBERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: false
    PARAMETERS:
        max_word_len: 512
        max_category_len: 128
    direct_path: ../data-direct/sentence_embedding_content_category_select

TOKENIZER:
    name: RoBERTa_dualbert
    pretrained_model_name_or_path: klue/roberta-base

TRAIN:
    batch_size: 32
    num_workers: 0

RESULT:
    savedir: ../data-direct/sentence_embedding_content_category_select
    dataname: RoBERTa_DualBERT_w512