EXP_NAME: RoBERTa_DualBERT-sentence_embedding_content_category_select
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: RoBERTa_DualBERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data-direct/sentence_embedding_content_category_select/RoBERTa_DualBERT_w512
    PARAMETERS:
        max_word_len: 512
        max_category_len: 128
    direct_path: ../data-direct/sentence_embedding_content_category_select

TOKENIZER:
    name: RoBERTa_dualbert
    
MODEL:
    modelname: RoBERTa_dualbert
    PARAMETERS:
        pretrained_name: 'klue/roberta-base'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: null

TRAIN:
    batch_size: 4
    num_training_steps: 10000
    accumulation_steps: 2
    num_workers: 0
    use_wandb: True

LOG:
    log_interval: 1
    eval_interval: 1000

OPTIMIZER:
    lr: 0.00001
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: ./saved_model-direct/sentence_embedding_content_category_select