EXP_NAME: BERT
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - validation
        - test

DATASET:
    name: BERT_category
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/BERT_Category
    PARAMETERS:
        max_word_len: 512
        use_cat: True

TOKENIZER:
    name: bert
    pretrained_model_name_or_path: 'skt/kobert-base-v1'

MODEL:
    modelname: bert
    PARAMETERS:
        pretrained_name: 'skt/kobert-base-v1'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: /saved_model/Part1/BERT_Category/best_model.pt
    Exp_Params:
        hidden_size: None
        num_layers: None
        
TRAIN:
    batch_size: 64
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: '/saved_model/Part1'
    result_name: results
