EXP_NAME: T5EncNet-tfidf_title_category_select
SEED: 223
MODE:
    save_list:
        - train
        - validation
        - test
DATASET:
  name: T5EncNet
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_source_length: 512
  direct_path: ../data-direct/tfidf_title_category_select
TOKENIZER:
  name: KETI-AIR/ke-t5-small-newslike
TRAIN:
  batch_size: 256
  num_workers: 12
RESULT:
  savedir: ../data-direct/tfidf_title_category_select
  dataname: T5EncNet_s512
