EXP_NAME: Multimodal_net-tfidf_content_category_select
SEED: 223
MODE:
  save_list:
    - train
    - validation
    - test
DATASET:
  name: Multimodal_net
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_word_len: 512
  direct_path: ../data-direct/tfidf_content_category_select
  CAT_KEYS: ["newsCategory","newsSubcategory","partNum","processType","processPattern","processLevel"]

TOKENIZER:
  name: bert
  pretrained_model_name_or_path: 'skt/kobert-base-v1'
TRAIN:
  batch_size: 1024
  num_workers: 12
RESULT:
  savedir: ../data-direct/tfidf_content_category_select
  dataname: Multimodal_net