EXP_NAME: RoBERTa_LSTM
SEED: 223
    
MODE:
    save_list:
        - train
        - validation
        - test

DATASET:
    name: BERT_LSTM
    data_path: ../data/Part1 # news article directory
    saved_data_path: false
    PARAMETERS:
        max_word_len: 512
        use_cat: True
    direct_path: ../data-direct/sentence_embedding_content_category_select

TOKENIZER:
    name: RoBERTa
    pretrained_model_name_or_path: klue/roberta-base

TRAIN:
    batch_size: 32
    num_workers: 4

RESULT:
    savedir: ../data-direct/sentence_embedding_content_category_select
    dataname: 'RoBERTa_LSTM'
