EXP_NAME: BERT_Sims_Stop_Gradient-sentence_embedding_title_category_select
SEED: 223
MODE:
  do_train: false
  do_test: true
  test_list:
  # - train
  # - validation
  - test
DATASET:
  name: BERT_CAT_CONT_LEN
  data_path: ../data/Part1
  saved_data_path: ../data-direct/sentence_embedding_title_category_select/BERT_CAT_CONT_LEN_w512
  PARAMETERS:
    max_word_len: 512
    cat_keys: ["newsCategory","newsSubcategory","partNum","processType","processPattern","processLevel"]

  direct_path: ../data-direct/sentence_embedding_title_category_select
TOKENIZER:
  name: bert
MODEL:
  modelname: bert_sims_stop_gradient
  PARAMETERS:
    pretrained_name: skt/kobert-base-v1
    num_classes: 2
  CHECKPOINT:
    checkpoint_path: ./saved_model-direct/sentence_embedding_title_category_select/BERT_Sims_Stop_Gradient-sentence_embedding_title_category_select/best_model.pt
TRAIN:
  batch_size: 64
  num_workers: 12
LOG:
  log_interval: 10
RESULT:
  savedir: ./saved_model-direct/sentence_embedding_title_category_select
  result_name: results
