EXP_NAME: Multimodal_net-sentence_embedding_title_category_select
SEED: 223
MODE:
  do_train: False
  do_test: True
  test_list:
  - train
  - validation
  - test
DATASET:
  name: Multimodal_net
  data_path: ../data/Part1
  saved_data_path: ../data-direct/sentence_embedding_title_category_select/Multimodal_net
  PARAMETERS:
    max_word_len: 512
    cat_keys: ["newsCategory","newsSubcategory","partNum","processType","processPattern","processLevel"]
  direct_path: ../data-direct/sentence_embedding_title_category_select

TOKENIZER:
  name: bert
  pretrained_model_name_or_path: 'skt/kobert-base-v1'
  
MODEL:
  modelname: Multimodal_net
  PARAMETERS:
    pretrained_name: skt/kobert-base-v1
    num_classes: 2
  CHECKPOINT:
    checkpoint_path: ./saved_model-direct/sentence_embedding_title_category_select/Multimodal_net-sentence_embedding_title_category_select/best_model.pt
TRAIN:
  batch_size: 64
  num_workers: 12
LOG:
  log_interval: 10
RESULT:
  savedir: ./saved_model-direct/sentence_embedding_title_category_select
  result_name: results
